/* tablelist: DATASETMAP,HLTSTREAMDATASET,TABLESHARDS,TRGHLTSEEDMAP,TIMEINDEX,TRGBITMAP,RUNINFO,DATATAGS,IDS_DATATAG,L1SEEDMAP,HLTPATHMAP */
CREATE TABLE DATASETMAP(DATASETID NUMBER(10) ,DATASETNAME VARCHAR2(4000) ,CONSTRAINT DATASETMAP_PK PRIMARY KEY(DATASETID));
GRANT SELECT ON "DATASETMAP" TO PUBLIC;

CREATE TABLE HLTSTREAMDATASET(HLTPATHID NUMBER(10) ,STREAMID NUMBER(10) ,STREAMLABEL VARCHAR2(4000) ,DATASETID NUMBER(10) ,CONSTRAINT HLTSTREAMDATASET_PK PRIMARY KEY(HLTPATHID,STREAMID,DATASETID));
GRANT SELECT ON "HLTSTREAMDATASET" TO PUBLIC;

CREATE TABLE TABLESHARDS(ID NUMBER(5) ,MINRUN NUMBER(10) ,MAXRUN NUMBER(10) ,CONSTRAINT TABLESHARDS_PK PRIMARY KEY(ID));
GRANT SELECT ON "TABLESHARDS" TO PUBLIC;

CREATE TABLE TRGHLTSEEDMAP(HLTPATHID NUMBER(10) ,HLTCONFIGID NUMBER(10) ,L1SEEDID NUMBER(10) ,CONSTRAINT TRGHLTSEEDMAP_PK PRIMARY KEY(HLTPATHID,HLTCONFIGID,L1SEEDID));
GRANT SELECT ON "TRGHLTSEEDMAP" TO PUBLIC;

CREATE TABLE TIMEINDEX(FILLNUM NUMBER(10) ,RUNNUM NUMBER(10) ,LSNUM NUMBER(10) ,TIMESTAMPSEC NUMBER(10) ,TIMESTAMPMSEC NUMBER(10) ,TIMESTAMPSTR VARCHAR2(4000) ,WEEKOFYEAR NUMBER(5) ,DAYOFYEAR NUMBER(5) ,DAYOFWEEK NUMBER(5) ,YEAR NUMBER(5) ,MONTH NUMBER(5) ,CONSTRAINT TIMEINDEX_PK PRIMARY KEY(RUNNUM,LSNUM));
GRANT SELECT ON "TIMEINDEX" TO PUBLIC;

CREATE TABLE TRGBITMAP(BITNAMEID NUMBER(5) ,BITID NUMBER(5) ,BITNAME VARCHAR2(4000) ,CONSTRAINT TRGBITMAP_PK PRIMARY KEY(BITNAMEID));
GRANT SELECT ON "TRGBITMAP" TO PUBLIC;

CREATE TABLE RUNINFO(DATATAGID NUMBER(20) ,RUNNUM NUMBER(10) ,HLTKEY VARCHAR2(4000) ,HLTCONFIGID NUMBER(10) ,GT_RS_KEY VARCHAR2(4000) ,TRGMASK1 NUMBER(10) ,TRGMASK2 NUMBER(10) ,TRGMASK3 NUMBER(10) ,TRGMASK4 NUMBER(10) ,TRGMASK5 NUMBER(10) ,TRGMASK6 NUMBER(10) ,FILLSCHEME VARCHAR2(4000) ,NCOLLIDINGBX NUMBER(5) ,BXPATTERN BLOB ,NBPERLS NUMBER(5) ,CONSTRAINT RUNINFO_PK PRIMARY KEY(DATATAGID));
GRANT SELECT ON "RUNINFO" TO PUBLIC;

CREATE TABLE DATATAGS(DATATAGNAMEID NUMBER(20) ,DATATAGNAME VARCHAR2(4000) ,CREATIONUTC VARCHAR2(4000) ,COMMENTS VARCHAR2(4000) ,CONSTRAINT DATATAGS_PK PRIMARY KEY(DATATAGNAMEID),CONSTRAINT DATATAGS_UQ UNIQUE (DATATAGNAME));
GRANT SELECT ON "DATATAGS" TO PUBLIC;

CREATE TABLE IDS_DATATAG(DATATAGNAMEID NUMBER(20) ,DATATAGID NUMBER(20) ,FILLNUM NUMBER(10) ,RUNNUM NUMBER(10) ,LSNUM NUMBER(10) ,TIMESTAMPSEC NUMBER(10) ,CMSON NUMBER(1) ,NORB NUMBER(10) ,TARGETEGEV NUMBER(5) ,BEAMSTATUS VARCHAR2(4000) ,AMODETAG VARCHAR2(4000) ,CONSTRAINT IDS_DATATAG_PK PRIMARY KEY(DATATAGID),CONSTRAINT IDS_DATATAG_UQ UNIQUE (DATATAGNAMEID,RUNNUM,LSNUM)) PARTITION BY RANGE(RUNNUM) (PARTITION R1A VALUES LESS THAN (184000), PARTITION R1B VALUES LESS THAN (212000), PARTITION R2A VALUES LESS THAN (MAXVALUE));
GRANT SELECT ON "IDS_DATATAG" TO PUBLIC;

CREATE TABLE L1SEEDMAP(L1SEEDID NUMBER(10) ,L1SEED VARCHAR2(4000) ,CONSTRAINT L1SEEDMAP_PK PRIMARY KEY(L1SEEDID));
GRANT SELECT ON "L1SEEDMAP" TO PUBLIC;

CREATE TABLE HLTPATHMAP(HLTPATHID NUMBER(10) ,HLTPATHNAME VARCHAR2(4000) ,CONSTRAINT HLTPATHMAP_PK PRIMARY KEY(HLTPATHID));
GRANT SELECT ON "HLTPATHMAP" TO PUBLIC;
