/* tablelist: IOVP_BOOLEAN,IOVP_STRING,IOVTAGDATA,IOVP_BLOB,IOVP_FLOAT,IOVP_INT,IOVP_SMALLINT,IOVTAGS */
DROP TABLE IOVP_BOOLEAN CASCADE CONSTRAINTS;
DROP TABLE IOVP_STRING CASCADE CONSTRAINTS;
DROP TABLE IOVTAGDATA CASCADE CONSTRAINTS;
DROP TABLE IOVP_BLOB CASCADE CONSTRAINTS;
DROP TABLE IOVP_FLOAT CASCADE CONSTRAINTS;
DROP TABLE IOVP_INT CASCADE CONSTRAINTS;
DROP TABLE IOVP_SMALLINT CASCADE CONSTRAINTS;
DROP TABLE IOVTAGS CASCADE CONSTRAINTS;