/* tablelist: HLT_&SUFFIX,DEADTIME_&SUFFIX,PXL_&SUFFIX,HFOC_&SUFFIX,ONLINE_RESULT_&SUFFIX,PLT_RESULT_&SUFFIX,BCMF_RESULT_&SUFFIX,HFET_RESULT_&SUFFIX,HFOC_RESULT_&SUFFIX,TRG_&SUFFIX,BEAM_&SUFFIX,OFFLINE_RESULT_&SUFFIX,PLT_&SUFFIX,BCMF_&SUFFIX,HFET_&SUFFIX */
DROP TABLE HLT_3 CASCADE CONSTRAINTS;
DROP TABLE DEADTIME_3 CASCADE CONSTRAINTS;
DROP TABLE PXL_3 CASCADE CONSTRAINTS;
DROP TABLE HFOC_3 CASCADE CONSTRAINTS;
DROP TABLE ONLINE_RESULT_3 CASCADE CONSTRAINTS;
DROP TABLE PLT_RESULT_3 CASCADE CONSTRAINTS;
DROP TABLE BCMF_RESULT_3 CASCADE CONSTRAINTS;
DROP TABLE HFET_RESULT_3 CASCADE CONSTRAINTS;
DROP TABLE HFOC_RESULT_3 CASCADE CONSTRAINTS;
DROP TABLE TRG_3 CASCADE CONSTRAINTS;
DROP TABLE BEAM_3 CASCADE CONSTRAINTS;
DROP TABLE OFFLINE_RESULT_3 CASCADE CONSTRAINTS;
DROP TABLE PLT_3 CASCADE CONSTRAINTS;
DROP TABLE BCMF_3 CASCADE CONSTRAINTS;
DROP TABLE HFET_3 CASCADE CONSTRAINTS;