/* tablelist: DATASETMAP,HLTSTREAMDATASET,TABLESHARDS,TRGHLTSEEDMAP,TIMEINDEX,TRGBITMAP,RUNINFO,DATATAGS,IDS_DATATAG,L1SEEDMAP,HLTPATHMAP */
DROP TABLE DATASETMAP CASCADE CONSTRAINTS;
DROP TABLE HLTSTREAMDATASET CASCADE CONSTRAINTS;
DROP TABLE TABLESHARDS CASCADE CONSTRAINTS;
DROP TABLE TRGHLTSEEDMAP CASCADE CONSTRAINTS;
DROP TABLE TIMEINDEX CASCADE CONSTRAINTS;
DROP TABLE TRGBITMAP CASCADE CONSTRAINTS;
DROP TABLE RUNINFO CASCADE CONSTRAINTS;
DROP TABLE DATATAGS CASCADE CONSTRAINTS;
DROP TABLE IDS_DATATAG CASCADE CONSTRAINTS;
DROP TABLE L1SEEDMAP CASCADE CONSTRAINTS;
DROP TABLE HLTPATHMAP CASCADE CONSTRAINTS;